#!/bin/bash
for i in *.jpg ; do
	j=$(echo "$i" | sed 's/[_-]/ /g ; s/\.jpg/ .jpg/')
	a=($j)
	if [ "x${a[0]}${a[1]}" = "x${b[0]}${b[1]}" ] ; then
		a[3]="${b[3]}"
		a[4]='X'
		msg='<----date'
	elif [[ "x${a[3]}" < "x${b[3]}" ]] ; then
		(( a[3] = 10#${b[3]} + 1 ))
		a[3]=$(printf '%04d' ${a[3]})
		msg='<----sequence'
	fi
	fixed=$(echo "${a[*]}" | sed 's/ \.jpg/.jpg/ ; s/ /_/g')
	newname=$(echo "${a[*]}" | sed 's/ \.jpg/.r.jpg/ ; s/ /_/g')
	if [ "$i" != "$fixed" ] ; then
		echo "$i" "$newname" "$msg"
	else
		echo "$i"
	fi
	msg=
	b=(${a[*]})
done
