#!/bin/bash

. "${HOME}/bin/general_header"

# Constants

alert_fmt="%-20s %-20s $ColourOn${Red}m%-20s $ColourOn${Brown}m%-30s $ColourOn${Cyan}m%s$ColourOff"
printval_fmt="%-20s %-20s $ColourOn${White}m%20s $ColourOn${Cyan}m%-30s$ColourOff"
alert_type=short

# Functions

function progress {

	. "${bin}/show-progress"

}

# Init

exec 7>db
exec 8>log

. "${bin}/start"

exec 6<input

# Main

while read l ; do

	echo "${l[*]:0:2 ${l[*]:3}" | \

	sed 's/\(.*\)[[:space:]]\+\.\/.*/\1/'

	progress

done

# Footer

# . "${bin}/general_footer"

# End
