#!/bin/bash
. "${HOME}/bin/general_header"
. "${bin}/${myname}_header"
thisfile="main"

#!/bin/bash

. "${HOME}/bin/pic_setup_header"
. "${bin}/ask-continue"

thisfile="main"
count=0
while read -a a ; do
	sum="${a[0]}"
	setfile="${input}.files/${sum}.files"
	echo "$sum" >&2
	if [[ "$debug" ]] ; then
		printval "sum" "$sum"
		printval "setfile" "$setfile"
	fi
	if [ -f "$setfile" ] ; then
		exec 5<"$setfile"
		ccount=0
		while read pline ; do
			(( ccount++ ))
			picture=$(echo "$pline" | sed 's/[^ ]* *\(.*\)/\1/ ; s/\.pic//')
			choices[$ccount]="$picture"
			feh "$picture" &
		done <&5
		exec 5<&-
		filecount=0
		resultfile="${setfile}.result"
		exec 8<"$resultfile"
		while read line ; do
			a=($line)
			case "${a[0]}" in
				'SUMMARY')
					filecount="${a[1]}"
					echo "$line" | grep -E "($filecount)|(^)" --color=auto
					;;
				'<')
					echo "$line" | grep -E "(^<)|(\[)|(\])|( [-:])|( 0x)" --color=auto
					;;
				'>')
					echo "$line"
					;;
				"$filecount")
					echo "$line" | grep -E "(^$filecount)" --color=auto
					;;
				"TABLE")
					filecount=0
					echo "$line"
					;;
				*)
					echo "$line"
					;;
			esac
		done <&8
	fi
	echo
	. "${bin}/show-progress"
	echo
	echo
	echo "Enter file numbers to delete"
	echo
	cat -n "$setfile"
	echo
	select i in "${choices[@]}" ; do
		mv "$i" "deleteme_$i"
		choices[$REPLY]="flagged: $i"
	done </dev/tty
	exit
	echo "$delnums" > "${setfile}.del"
done <&6
. "${bin}/pic_setup_footer"
. "${bin}/do-${myname}_footer"
