#!/bin/bash

# fix

#bindir="$bin" # Obsolete. .bash_profile does this now.

file="$bindir/$1"
template="$bindir"/template
if ! [ -e "$bindir" ] ; then
	mkdir "$bindir"
fi
if ! [ -d "$bindir" ] ; then
	ls -l "$bindir"
	echo "fix: $bindir needs to _exist_ and be a directory."
	exit 1
fi
if [ "x$1" = "x" ] ; then
	showbin
	echo "fix: Missing a filename."
	exit 1
fi
if ! [ -e $file ] ; then
	cp $template "$file"
fi
if [ -f "$file" ] ; then
	# nano -c "$file"   # This was the old way.
	configure "$file"
else
	echo "$file" needs to exist and be a regular file.
	echo If you intended to create a new file "$file", there might be a problem with the new-file template or this script.
	exit 1
fi
chmod 775 "$file"
ls -latr "$file"*
