#!/bin/bash

. "${HOME}/bin/general_header"

if [ x"$1" = x ] ; then
	echo ERROR: Missing a file name.
	exit 1
fi

input="$1"

exec 6<input

# MAIN

sed -f '
s/^\([0-9]\{6\}\.[0-9]\{4\} .*\)$/----------\1/
s/^----------\([0-9]\{6\}\.[0-9]\{4\} .*\)$/----------\1/
'
<&6

# END
