#!/bin/bash

. "${HOME}/bin/general_header"

# Constants

alert_fmt="%-20s %-20s $ColourOn${Red}m%-20s $ColourOn${Brown}m%-30s $ColourOn${Cyan}m%s$ColourOff"
printval_fmt="%-20s %-20s $ColourOn${White}m%20s $ColourOn${Cyan}m%-30s$ColourOff"
alert_type=short

# Globals for function show_progress and start

total=
count=
wid=
input=

# Functions

function progress {

	. "${bin}/show-progress"

}

# Init

exec 7>db
exec 8>log

. "${bin}/start" # 'start' needs to count the lines in the file 'input'

exec 6<input

# Main

progress

# Footer

# . "${bin}/general_footer"

# End
