#!/bin/bash
. '/home/jim/bin/_pic_analysis_header'

echo "Generating list of $type files..."
find -name "*$1" -type f > "$list".tmp
cat "$list".tmp | sort > "$list"
rm "$list".tmp
. ${bin}/_count_list_lines
echo "$lines $1 files found."
