#!/bin/bash

. "${HOME}/bin/general_header"

f="$1"
#printvar f
if ! [ -e "$f" ] ; then
	#echo "I can't find '$f'"
	exit 1
fi

line=$(cat "$f" | grep -E -m 1 "(^Sent:)")
#printvar line

#str="$(cat "$f" | grep -E -m 1 "(^Sent:)" | sed 's/^Sent:[[:space:]]\+\([^[:space:]]\+\)[[:space:]]\+[^[:space:]]\+[[:space:]]\+[^[:space:]]\+[[:space:]]\+\(.*\)//')"
str="$(cat "$f" | grep -E -m 1 "(^Sent:)" | sed 's/^Sent:[[:space:]]\+\([^[:space:]]\+\)[[:space:]]\+[^[:space:]]\+[[:space:]]\+[^[:space:]]\+[[:space:]]\+\(.*\)/\1 \2/')"

#printvar str

dat=$(date -d "$str" +%y%m%d.%H%M%S)
#printvar dat

echo "$dat"
