#!/bin/bash

echo Char: $1 File: $2
grep -E "($(echo -e "\x$1"))" $2
echo -e "\x$1" >"$1".char
iconv -f windows-1252 "$1".char >"$1".char.utf8
read newchar <"$1".char.utf8
echo
echo Char: $1 $(cat "$1".char.utf8) File: $2
grep -E "($(echo -e "\x$1"))" $2 | sed "s/\x$1/$newchar/"
