#!/bin/bash

. "${HOME}/bin/general_header"

mount | grep -Ev "(/boot)|(on /dev)|(/proc)|(/run)|(/sys)" | sed 's/ on / / ; s/ type / /' | sort -k2 | align | sed 's/ ext\([[:digit:]]\+\) / \x1b[1;34mext\1\x1b[0m / ; s/ ntfs / \x1b[1;33mntfs\x1b[0m /'
