#!/bin/bash

c1=4
c2=2
c3=50
p1=' '
p2='  '
p3="$p1$p2"
pn=${#p3}
(( n = $c1 + $c2 + $pn + 2 ))
echo > diskinfo
echo "# Disk Information $(date)" >> diskinfo
echo "# " >> diskinfo
ls -l /dev/disk/* | sed 's/.*16:[[:digit:]]\{2\}[[:space:]]*// ; s/total 0// ; s/-> \.\.\/\.\.// ; s/^[[:space:]]*$// ; s/\(\/[^[:digit:]]\+\)\([[:digit:]]\)/\1 \2/' | grep -Ev "(id:scsi-)|(id:dm-uuid-)" | while read -a a ; do printf "%-${c3}s %-${c1}s%-${c2}s\n" "${a[0]}" "${a[1]}" "${a[2]}" ; done | sed 's/^/# /' >> diskinfo
echo >> diskinfo
echo "# Devices:" >> diskinfo
echo >> diskinfo
for i in id path label uuid ; do ls -l /dev/disk/by-$i | sed 's/.*16:[[:digit:]]\{2\}[[:space:]]*// ; s/total 0// ; s/-> \.\.\/\.\.// ; s/^\/.*// ; s/^[[:space:]]*$// ; s/\(\/[^[:digit:]]\+\)\([[:digit:]]\)/\1 \2/ ; s/^/'$i':/' | grep -Ev "(^$)|(id:scsi-)|(id:dm-uuid-)" | while read -a a ; do printf "%-${c1}s %${c2}s  %s\n" "${a[1]}" "${a[2]}" "${a[0]}" ; done ; done | sort -k1,1 -k2h | sed 's/^/# /' | uniq -w $n --all-repeated=separate >> diskinfo ; cat diskinfo
